exports.default = {
	'theme': 'default',
	'name': 'Docstrap',
	'description': 'Docstrap is an open-source library, allows you to generate documentation web-view for your projects in a organize and lightweight way',
	'discord': '#linktodiscord',
	'benefits': [
		`<div class="porperty">
			<i class="fas fa-feather-alt"></i>
			<h3>Lightweight</h3>
			<p>
				Docstrap scales well without adding overhead to the application. Generated files ara Plain vanilla HMTL-CSS-JS.
			</p>
		</div>`,
		`<div class="porperty">
			<i class="fas fa-tachometer-alt"></i>
			<h3>Fast</h3>
			<p>
				Docstrap use NodeJS alone, avoiding convoluted frameworks so your documentation can be generated by yourself or CI/CD process in an optimal way.
			</p>
		</div>`
	],
	'links': [
		`<a href="#expressif">
			<img src="img/expressif-boxmodel.jpeg" alt="expressif logo">
		</a>`,
		`<a href="#metaflux">
			<img src="img/metaflux-logo-black.svg" alt="expressif logo">
		</a>`
	],
	'repository': 'https://github.com/rebelstackio/docstrap.git'
}
